### ISSUE TITLE
Help all hackathon participants to have ENS name setup on their ETH address

### ISSUE THREAD

**Issue by makoto** [ensdomains/hack2018#3]
- Team name: TBD
- Team members
- Team leader: @chris-remus 

## Hack idea:

Even though this is ENS hackathon, there are still some participants who don't know how to set their ENS name into their ETH address (aka setting reverse record).

The on boarding process require the following

- Obtaining ens subdomain via https://now.ens.domains (if they don't have their own ENS names)
- Setting up subdomain and reverse record via https://manager.ens.domains

Extra bonus if we can create a simple documentation or screencast

## What area do you need help on?:

- Someone who knows how to set reverse record
- Someone who are willing to do documenting stuff
- Someone who are willing to do screencast

**Comment by graemeblackwood** [comment]
I CAN HAZ ENS?

**Comment by makoto** [comment]
@chris-remus @graemeblackwood anyone working on this? If not I will close the issue

**Comment by makoto** [comment]
No taker so I will close this.
