### ISSUE TITLE
Provide ENS event datasets to users as a resource to use during the hackathon

### ISSUE THREAD

**Issue by Arachnid** [ensdomains/hack2018#5]

**Comment by makoto** [comment]
@Arachnid Please add more description (eg: the general idea, what kind of data you are providing, the size and format of data, and what kind of skillset people need to tackle this problem).

**Comment by Arachnid** [comment]
The dataset is here: https://drive.google.com/a/notdot.net/file/d/1NmcG_xOvFlvsYfSTu-RaoNS7MzIN91Bm/view?usp=drivesdk

It contains dumps of all events in both the ENS registry and the .eth registrar from the launch until about a month ago.

Each file has one event per line, in JSON format, with event parameters decoded.

**Comment by Huanzhang89** [comment]
Need permission to access the file :(

**Comment by makoto** [comment]
@Huanzhang89 I can seem to be able to access it. Isn't it that you need to login using a google adress?

**Comment by makoto** [comment]
The dataset will be used as part of https://github.com/ensdomains/hack2018/issues/14
